### ISSUE TITLE
error in using pcfcross()

### ISSUE THREAD

**Issue by geofly1985** [spatstat/spatstat.explore#2]
Hi, 

I was trying to use pcfcross() to calculate the PCF for two markers in my dataset which contains 1M points.
I encountered this error, which I couldn't trace back to the source code, do you know why and at which function this error happens ? 
It seems this is due to character length limited by R, but I was thinking we can do some trick in the source code to get rid of this error.

Error in paste(deparse(expr, width.cutoff, ...), collapse = collapse) : 
  result would exceed 2^31-1 bytes

Thanks in advance !

**Comment by geofly1985** [comment]
I further found the problem actually happened at spatstat.geom::unnormdensity(),
but I cannot figure out how to get around this error, I am attaching the csv file that gives me this error. Can you please take a look ? Thanks ! 
[example.csv.zip](https://github.com/spatstat/spatstat.explore/files/10845303/example.csv.zip)

**Comment by baddstats** [comment]
Thanks for reporting this.

When you get an error, please type `traceback()` which will reveal the nested sequence of function calls that led to the error. (and send the output to us!)

In this case I am pretty sure that I understand the cause of the error. I will try to fix it. This may involve changes to `spatstat.utils` as well.

**Comment by baddstats** [comment]
What version of `spatstat.geom` are you using?

**Comment by baddstats** [comment]
Please install the development version of `spatstat.geom`, version `3.0-6.008` or later, from the GitHub repository. (Note: `spatstat.geom` not `spatstat.explore`.) Then please try your example again.

**Comment by baddstats** [comment]
This should now be fixed, in the current development versions of `spatstat.explore` and `spatstat.geom`. Please confirm.

**Comment by geofly1985** [comment]
Thank you ! it works after installing the latest development version of spatstat.explore and spatstat.geom
