### ISSUE TITLE
maptools archived

### ISSUE THREAD

**Issue by rsbivand** [spatstat/spatstat.explore#3]
@baddstats @rubak maptools was archived three days ago, so please do move to submit an updated version of spatstat.explore as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details. This also applies to spatstat.geom and spatstat.model. Coercion should go via the sf package.

**Comment by baddstats** [comment]
The dependency has been removed in the current development version. It will be submitted soon.
